Migrated from ~/bin to ~/Scripts.

diff --git a/update-shortcuts b/update-shortcuts
--- a/update-shortcuts
+++ b/update-shortcuts
@@ -2,7 +2,7 @@
 # Updates the shortcuts file.
 # Christopher Birkbeck 2018
 
-# Traverse the entire bin directory to find any new files.
+# Traverse the entire Scripts directory to find any new files.
 function add_new {
   cd "$1" || { echo "Error. Cannot find or make $1 Exiting." >2; Exit 1; }
 
@@ -20,7 +20,7 @@ function add_new {
 
       orginal=$(readlink -f "$file")
 
-      echo -e "alias $name=\"$orginal\"" >> "$HOME/bin/shortcuts"
+      echo -e "alias $name=\"$orginal\"" >> "$HOME/Scripts/shortcuts"
     fi
   done
 
@@ -29,9 +29,9 @@ function add_new {
 
 # Removes any duplicated lines.
 function remove_duplicates {
-  awk '!seen[$0]++' "$HOME/bin/shortcuts" > "$HOME/bin/shortcuts-tmp"
-  rm "$HOME/bin/shortcuts"
-  mv "$HOME/bin/shortcuts-tmp" "$HOME/bin/shortcuts"
+  awk '!seen[$0]++' "$HOME/Scripts/shortcuts" > "$HOME/Scripts/shortcuts-tmp"
+  rm "$HOME/Scripts/shortcuts"
+  mv "$HOME/Scripts/shortcuts-tmp" "$HOME/Scripts/shortcuts"
 }
 
 # Verifies any existing entries still exist.
@@ -43,13 +43,13 @@ function verify {
       echo "Found $current"
       continue
     else
-      sed -i -E -e "s,alias (.*)=\"$current\",,g" "$HOME/bin/shortcuts"
+      sed -i -E -e "s,alias (.*)=\"$current\",,g" "$HOME/Scripts/shortcuts"
     fi
-  done <"$HOME/bin/shortcuts"
+  done <"$HOME/Scripts/shortcuts"
 }
 
-cd "$HOME/bin" || mkdir "$HOME/bin" || { echo "Error. Cannot find or make $HOME/bin. Exiting." >2; Exit 1; }
+cd "$HOME/Scripts" || mkdir "$HOME/Scripts" || { echo "Error. Cannot find or make $HOME/Scripts. Exiting." >2; Exit 1; }
 
-add_new "$HOME/bin"
+add_new "$HOME/Scripts"
 remove_duplicates
 verify
